from __future__ import annotations
import os 
import json
import re
from pathlib import Path

import numpy as np
from tqdm.auto import tqdm

if not hasattr(np, "sctypes"):
    np.sctypes = {
        "int": [np.int8, np.int16, np.int32, np.int64],
        "uint": [np.uint8, np.uint16, np.uint32, np.uint64],
        "float": [np.float16, np.float32, np.float64],
        "complex": [np.complex64, np.complex128],
        "others": [np.bool_, np.bytes_, np.str_, np.object_],
    }
if not hasattr(np, "maximum_sctype"):
    def _maximum_sctype(t):
        dtype = np.dtype(t)
        if np.issubdtype(dtype, np.complexfloating):
            return np.complex128
        if np.issubdtype(dtype, np.floating):
            return np.float64
        if np.issubdtype(dtype, np.unsignedinteger):
            return np.uint64
        if np.issubdtype(dtype, np.integer):
            return np.int64
        return dtype.type

    np.maximum_sctype = _maximum_sctype

from calvin_utils.neuroimaging_utils.tract_utils.compute_connectivity import FiberConnectivity
from calvin_utils.neuroimaging_utils.tract_utils.fiber_intersection import FiberVoxelIndexer


class filter_fibers:
    """
    Generate patient-by-fiber connectivity profiles from a canonical fiber atlas.

    This is the notebook-facing orchestration class for fiber filtering. It takes
    a dataframe containing patient NIfTI paths, builds a voxel index for a shared
    fiber atlas, samples every patient NIfTI against that atlas, and writes:

    1. one ``.npy`` vector per patient, shape ``(n_fibers,)``
    2. an optional cohort matrix, shape ``(n_patients, n_fibers)``
    3. a manifest CSV/JSON tying dataframe rows to generated fiber vectors

    Required inputs
    ---------------
    df:
        A pandas DataFrame with one row per patient/observation.
    nifti_col:
        Name of the dataframe column containing patient NIfTI paths.
    fiber_atlas_path:
        Path to the canonical internal fiber atlas. This must be a Calvin
        ``.npz`` file with a ``fibers`` key, usually generated by
        ``ConnectomeSeed`` or ``FiberAtlasConverter``. External tract formats
        such as ``.tck``/``.trk`` should be converted once before entering this
        pipeline.
    reference_nifti_path:
        NIfTI defining the voxel grid used to rasterize fibers. Patient NIfTIs
        are resampled to this grid if shape or affine differ. This should be in
        the same world/MNI space as the fiber atlas.
    out_dir:
        Directory where patient vectors, matrix, and manifests are written.

    Common options
    --------------
    patient_id_col:
        Optional dataframe column used to name output patient vector files. If
        omitted, names are derived from each NIfTI filename.
    mode:
        How voxel values are reduced onto each fiber:
        ``"binary"`` = 1 if the patient image touches the fiber, else 0.
        ``"max"`` = maximum patient-image value along the fiber.
        ``"mean"`` = mean patient-image value along the fiber.
        ``"sum"`` = sum of patient-image values along the fiber.
    binarize:
        If True, threshold the patient image before querying which fibers are
        touched. For binary masks, use ``binarize=True`` and ``threshold=0``.
    threshold:
        Threshold used when ``binarize=True``.
    step_size_vox:
        Fiber rasterization step size in reference-image voxel units. Smaller
        values sample fiber segments more densely but are slower.
    save_matrix:
        If True, save the stacked patient-by-fiber matrix.

    Return value
    ------------
    ``run()`` returns a copy of the input dataframe with a new
    ``fiber_profile_path`` column. Full run metadata remains available through
    ``get_result()`` or ``self.result`` after ``run()`` completes:

        ``profile_paths``: list of per-patient ``.npy`` files
        ``matrix``: stacked ``float32`` matrix, shape ``(n_patients, n_fibers)``
        ``matrix_path``: path to saved matrix, or None
        ``manifest_csv``: path to saved manifest CSV
        ``manifest_json``: path to saved run metadata JSON

    Notes
    -----
    The ``run()`` method intentionally contains only method calls. All pipeline
    logic lives in named methods so notebooks can call the high-level class
    without exposing implementation details.
    """

    def __init__(
        self,
        df,
        nifti_col: str,
        fiber_atlas_path: str | Path,
        reference_nifti_path: str | Path,
        out_dir: str | Path,
        *,
        patient_id_col: str | None = None,
        mode: str = "binary",
        binarize: bool = True,
        threshold: float | None = 0,
        step_size_vox: float = 0.5,
        fiber_mask=None,
        profile_suffix: str = "_fiber_connectivity",
        save_matrix: bool = True,
        matrix_name: str = "cohort_fiber_connectivity_matrix.npy",
        manifest_name: str = "fiber_filter_manifest",
        show_progress: bool = True,
    ):
        self.df = df.copy()
        self.nifti_col = nifti_col
        self.fiber_atlas_path = Path(fiber_atlas_path)
        self.reference_nifti_path = Path(reference_nifti_path)
        self.out_dir = Path(out_dir)
        self.patient_id_col = patient_id_col
        self.mode = mode
        self.binarize = bool(binarize)
        self.threshold = threshold
        self.step_size_vox = float(step_size_vox)
        self.fiber_mask = fiber_mask
        self.profile_suffix = profile_suffix
        self.save_matrix = bool(save_matrix)
        self.matrix_name = matrix_name
        self.manifest_name = manifest_name
        self.show_progress = bool(show_progress)

        self.nifti_paths = None
        self.patient_ids = None
        self.indexer = None
        self.mapper = None
        self.profile_paths = []
        self.matrix = None
        self.matrix_path = None
        self.manifest_csv = None
        self.manifest_json = None
        self.result = None

    def validate_inputs(self):
        if self.nifti_col not in self.df.columns:
            raise ValueError(f"nifti_col '{self.nifti_col}' is not present in df.")
        if self.patient_id_col is not None and self.patient_id_col not in self.df.columns:
            raise ValueError(f"patient_id_col '{self.patient_id_col}' is not present in df.")
        if self.df.empty:
            raise ValueError("df is empty.")
        if not self.fiber_atlas_path.exists():
            raise FileNotFoundError(f"fiber_atlas_path does not exist: {self.fiber_atlas_path}")
        if self.fiber_atlas_path.suffix.lower() != ".npz":
            raise ValueError(
                "filter_fibers requires a Calvin .npz fiber atlas. Convert external tract files first, e.g.\n"
                "from calvin_utils.neuroimaging_utils.tract_utils.fiber_atlas_converter import FiberAtlasConverter\n"
                "FiberAtlasConverter(input_path='atlas.tt.tck', out_path='atlas.npz').run()"
            )
        self._validate_npz_atlas(self.fiber_atlas_path)
        if not self.reference_nifti_path.exists():
            raise FileNotFoundError(f"reference_nifti_path does not exist: {self.reference_nifti_path}")
        if self.mode not in {"binary", "max", "mean", "sum"}:
            raise ValueError("mode must be one of: binary, max, mean, sum.")
        if self.binarize and self.threshold is None:
            raise ValueError("threshold must be provided when binarize=True.")

    def prepare_output_dirs(self):
        self.out_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _validate_npz_atlas(path):
        obj = np.load(path, allow_pickle=True)
        if "fibers" not in obj:
            raise ValueError(f"fiber_atlas_path is not a Calvin fiber atlas; missing 'fibers' key: {path}")

    def resolve_nifti_paths(self):
        self.nifti_paths = [Path(path) for path in self.df[self.nifti_col].tolist()]
        missing = [str(path) for path in self.nifti_paths if not path.exists()]
        if missing:
            raise FileNotFoundError(f"Missing patient NIfTI files: {missing[:10]}")

    def resolve_patient_ids(self):
        if self.patient_id_col is None:
            raw_ids = [self._nifti_stem(path) for path in self.nifti_paths]
        else:
            raw_ids = [str(value) for value in self.df[self.patient_id_col].tolist()]
        self.patient_ids = self._make_unique_ids(raw_ids)

    def build_indexer(self):
        self.indexer = FiberVoxelIndexer.from_fiber_file(
            fiber_file_path=str(self.fiber_atlas_path),
            reference_nifti_path=str(self.reference_nifti_path),
            fiber_mask=self.fiber_mask,
            step_size_vox=self.step_size_vox,
        )

    def build_mapper(self):
        self.mapper = FiberConnectivity(fiber_indexer=self.indexer, mode=self.mode)

    def _get_fname(self, nifti_path):
        fiber_dir = Path(nifti_path).parents[1] / "fibers"      # make a parallel dir
        if nifti_path.name.endswith(".nii.gz"):  # Fixes bad handling of double suffix
            stem = nifti_path.name[:-7]
        else:
            stem = nifti_path.stem
        fname = fiber_dir / f"{stem}_{self.fiber_atlas_path.stem}.fib.npy"
        os.makedirs(fiber_dir, exist_ok=True)
        return fname

    def generate_and_save_profiles(self):
        vectors = []
        iterator = self._progress(
            zip(self.patient_ids, self.nifti_paths),
            total=len(self.nifti_paths),
            desc="Filtering patient fibers",
            unit="patient",
        )
        for patient_id, nifti_path in iterator:
            nifti_path = Path(nifti_path)
            vector = self.mapper.generate_connectivity_profile(nifti_path=str(nifti_path), binarize=self.binarize, threshold=self.threshold)
            fname = self._get_fname(nifti_path)
            np.save(fname, vector.astype(np.float32))
            self.profile_paths.append(fname)
            vectors.append(vector)
        self.matrix = np.vstack(vectors).astype(np.float32)

    def save_cohort_matrix(self):
        if not self.save_matrix:
            return
        self.matrix_path = self.out_dir / self.matrix_name
        np.save(self.matrix_path, self.matrix)

    def attach_profile_paths_to_df(self):
        self.df["fiber_path"] = [str(path) for path in self.profile_paths]

    def save_manifest(self):
        self.manifest_csv = self.out_dir / f"{self.manifest_name}.csv"
        self.manifest_json = self.out_dir / f"{self.manifest_name}.json"
        self.df.to_csv(self.manifest_csv, index=False)
        self.manifest_json.write_text(json.dumps(self._metadata(), indent=2))

    def package_result(self):
        self.result = {
            "df": self.df,
            "profile_paths": [str(path) for path in self.profile_paths],
            "matrix": self.matrix,
            "matrix_path": str(self.matrix_path) if self.matrix_path is not None else None,
            "manifest_csv": str(self.manifest_csv),
            "manifest_json": str(self.manifest_json),
        }

    def get_result(self):
        return self.result

    def get_dataframe(self):
        return self.df

    def _metadata(self):
        return {
            "fiber_atlas_path": str(self.fiber_atlas_path),
            "reference_nifti_path": str(self.reference_nifti_path),
            "out_dir": str(self.out_dir),
            "nifti_col": self.nifti_col,
            "patient_id_col": self.patient_id_col,
            "mode": self.mode,
            "binarize": self.binarize,
            "threshold": self.threshold,
            "step_size_vox": self.step_size_vox,
            "profile_suffix": self.profile_suffix,
            "save_matrix": self.save_matrix,
            "matrix_name": self.matrix_name,
            "n_patients": len(self.nifti_paths),
            "n_fibers": int(self.matrix.shape[1]) if self.matrix is not None else None,
            "profile_paths": [str(path) for path in self.profile_paths],
        }

    def _progress(self, iterable, **kwargs):
        if not self.show_progress:
            return iterable
        return tqdm(iterable, **kwargs)

    @staticmethod
    def _nifti_stem(path: Path):
        if path.name.endswith(".nii.gz"):
            return path.name[:-7]
        return path.stem

    @classmethod
    def _make_unique_ids(cls, raw_ids):
        seen = {}
        unique_ids = []
        for raw_id in raw_ids:
            clean = cls._sanitize_id(raw_id)
            count = seen.get(clean, 0)
            seen[clean] = count + 1
            unique_ids.append(clean if count == 0 else f"{clean}_{count + 1}")
        return unique_ids

    @staticmethod
    def _sanitize_id(value):
        clean = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value).strip())
        clean = clean.strip("._-")
        return clean or "patient"
    
    ### Orchestration ###
    def run(self):
        self.validate_inputs()
        self.prepare_output_dirs()
        self.resolve_nifti_paths()
        self.resolve_patient_ids()
        self.build_indexer()
        self.build_mapper()
        self.generate_and_save_profiles()
        self.save_cohort_matrix()
        self.attach_profile_paths_to_df()
        self.save_manifest()
        self.package_result()
        return self.get_dataframe()


FilterFibers = filter_fibers
